### PR TITLE
added a drush command to build the project

### PR DESCRIPTION
**Pull request by mordonez**

### CODE REVIEW

**Comment by q0rban** [comment]
Hmm, interesting. I'm hesitant to add this because it makes a lot of assumptions about how to update, or "build", a Drupal site. We have many projects where the steps to deploy are very unique to that project. What are your thoughts, @blakehall?

**Comment by blakehall** [comment]
I think the idea of having a "build project" command makes a _ton_ of sense. Ideally I'd like to see it be a bit more configurable. Perhaps a meta-command that allows a bit more configuration around what "build" actually means, but is at least a consistent drush task that we can include in jenkins jobs. In other words, we could rely on calling `drush jgd-build` but the tasks that actually make up the build process would need to be overridden in a local config file.

**Comment by q0rban** [comment]
I guess I'm thinking that it's not the responsibility of Tugboat to know how to build a project.

**Comment by blakehall** [comment]
I think I'd agree that it's not Tugboat's responsibility to know _how_ to build a project, but having a generic "build" command seems logical.

**Comment by mordonez** [comment]
Sorry, yesterday was just playing with the repo to review the possibilities. And I made the pull request by error. But I'd agree I would be a must have a build command, maybe configurable depending of the project: 
- Tipical drupal deployment (drupal+contrib+custom...)
- Profile & drush make
- Multi-site
  ..

**Comment by q0rban** [comment]
The way we've typically done this on our current projects is to have a separate Jenkins job that calls a script to build any environment. This way it is consistently built across all environments—dev, tugboat, stage, qa, and prod. Which is why I don't think Tugboat should even worry about it.

**Comment by mordonez** [comment]
I close the pull request, thanks for your feedback.

**Pull request closed without merging**
