### PR TITLE
Add the option to do a full database clone instead of prefixed tables

### PR DESCRIPTION
**Pull request by bchavet**
The default behavior is still to use table prefixes, since that should work on any Drupal site. In order to use a full database clone, the -c option needs to be sent to clone_site.sh and cleanup.sh

### CODE REVIEW

**Comment by q0rban** [comment]
We'll need to be careful here, because once this gets merged, it has the ability to delete the source database itself (since existing environments share the source database).

**Comment by bchavet** [comment]
Existing sites will continue to use table prefixes. The full database clone/cleanup is opt-in.

**Comment by q0rban** [comment]
But they all use the same tugboat scripts, so when you run tear down on an existing tugboat environment, you will delete the source database. We ran into this on MSNBC. The easiest thing to do is just tear down all environments, then upgrade, then rebuild the environments.

**Comment by q0rban** [comment]
Talked this over with Ben, and we are completely destroying the old server, so we're not really worried about anything there.

**Pull request merged**
