### PR TITLE
beginning of this section from #5

### PR DESCRIPTION
**Pull request by sirkitree**
Beginning of overview section. Let's work on this in a pull request.

### CODE REVIEW

**Comment by sirkitree** [comment]
I think this is looking pretty good. @jjeff do you want to review the text here (click the "Files Changed" tab above to review) and merge if it looks good?

**Comment by jjeff** [comment]
Looks good. I'm merging. However, you guys have been calling it a "Pull Request Builder" and it doesn't say that anywhere in here. I was calling it Lullabot's Magical Jenkins/Github/Drupal Scripts, but should we call it Lullabot's Magical GitHub Pull Request Builder?

**Comment by sirkitree** [comment]
We're actually calling it tugboat I think. We had a discussion and ideas here: https://lullabot.hackpad.com/54eLwo2uTpr?r=0 and I think tugboat got the most votes.

**Comment by q0rban** [comment]
Tugboat is a good name for an app. I think the scripts themselves are ok to
stay named as they are. Thoughts otherwise?

**Pull request merged**
